USE Story
CREATE TABLE Categories
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50),
TShirt NVARCHAR(50),
Jeans NVARCHAR(50),
Shoes NVARCHAR(50),
Jacket NVARCHAR(50)
)

CREATE TABLE Products
(
Id INT PRIMARY KEY IDENTITY,
ProductCode INT,
CategoryId INT FOREIGN KEY REFERENCES Categories(Id)
)



CREATE TABLE Stock
(
ID INT PRIMARY KEY IDENTITY,
ProductId INT FOREIGN KEY REFERENCES Products(Id),
Count INT,
Size INT,
CreatedDate DATE
)

CREATE TABLE Sizes
(
Id INT PRIMARY KEY IDENTITY,

)

DROP TABLE Sizes
CREATE TABLE Sizes
(
Id INT PRIMARY KEY IDENTITY,
)
CREATE VIEW WIEW
WHERE ProductCode 1234, Categories.Name Sport, CreateDate 
